### ISSUE TITLE
 CLI can't found out my comfyUI

### ISSUE THREAD

**Issue by Wingto** [Comfy-Org/comfy-cli#197]
**Describe the bug**
I have setup comfyUI for portable zip package, but in CLI, i wrote down "comfy --recent launch", it return **"warn: No recent workspace has been set."**
![image](https://github.com/user-attachments/assets/7143a4bc-e2c1-4cce-80da-58d1bdca7ba2)
![image](https://github.com/user-attachments/assets/3fd0a071-f1ff-4542-8ae2-58c96c8c31c5)

**Comment by yoland68** [comment]
You can try setting the location of the directory (cli only tracks the recent launched instance from cli)

**Comment by yoland68** [comment]
@joanllabata Can you paste your outputs here and your result from running `comfy env`?

**Comment by joanllabata** [comment]
@yoland68 things got messy: 

1. I had originally installed comfy-cli as a package in a portable comfyUIinstall. 
2. as I was unable to point comfy-cli to the path to the portable install I installed a fresh comfy-cli on a venv 
3. now if I go back to the original portable install and run comfy env (the python embeded package) now it's showing a mix of the old comfy-cli and the new comfy-cli because it show the new workspace that was created with the new comfy-cli
